import type { Site } from "@/types";

export const siteConfig: Site = {
  name: "shaahid.xyz",
  title: "shaahid",
  description: "I design and develop web applications using Nextjs and sometimes write smart contracts using solidity",
  keywords: [
    "shaahid shaikh",
    "shaahid",
    "shaah1d",
    "portfolio",
    "shaahid portfolio",
    "shaahid 100x dev",
    "full stack developer",
    "designer",
    "web developer",
    "web designer",
    "react developer",
    "react designer",
    "next.js developer",
    "next.js designer",
    "shaahid shaikh portfolio",
    "shaahid shaikh website",
    "shaahid shaikh portfolio website",
    "shaahid shaikh portfolio website 2026",
    "shaahid shaikh portfolio 2026",
    "shaah1d",
    "shaah1d in",
    "shaah1d.in", 
    "shaah1d portfolio",
    "shaah1d portfolio 2026",
    "shaah1d portfolio website",
    "shaah1d portfolio website 2026",
    "shaah1d portfolio 2026 website",
    "shaah1d portfolio 2026 website 2026",
    "shaah1d portfolio 2026 website 2026",
    "shaah1d portfolio 2026",
    "shaah1d portfolio 2026 website",
    "shaah1d portfolio 2026 website 2026",
  ],
  siteUrl: "https://shaahid.xyz",
  creator: {
    name: "shaah1d",
    url: "https://shaahid.xyz",
  },
  ogImage: "https://shaahid.xyz/og.png",
  links: {
    x: "https://x.com/shaah1d",
    github: "https://github.com/shaah1d",
  }
}